import { StyleSheet } from "react-native";
import { Theme, paletteLight, paletteDark } from "./palettes";

export const makeStyles = (t: Theme) =>
  StyleSheet.create({
    screen: { flex: 1, backgroundColor: t.light },
    title: {
      fontSize: 28,
      fontWeight: "800",
      color: t.text,
      textAlign: "left",
      marginTop: 8,
      paddingHorizontal: 16,
    },
    subtitle: {
      fontSize: 12,
      color: t.subtle,
      textAlign: "left",
      paddingHorizontal: 16,
      marginBottom: 8,
    },
    header: {
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderBottomWidth: 1,
      backgroundColor: t.card,
      borderBottomColor: t.border,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    headerTitle: { fontSize: 20, fontWeight: "700", color: t.dark },
    headerSub: { fontSize: 12, color: t.subtle },
    headerRight: { flexDirection: "row", gap: 8 },
    addBar: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      padding: 12,
      backgroundColor: t.card,
      borderBottomWidth: 1,
      borderBottomColor: t.border,
    },
    filters: {
      flexDirection: "row",
      gap: 8,
      padding: 12,
      backgroundColor: t.card,
      borderBottomWidth: 1,
      borderBottomColor: t.border,
      justifyContent: "flex-start",
    },
    chip: {
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: t.border,
    },
    chipText: { fontSize: 12, fontWeight: "600", color: t.text },
    input: {
      minWidth: 200,
      height: 48,
      paddingHorizontal: 12,
      paddingVertical: 12,
      borderWidth: 1,
      borderColor: t.border,
      borderRadius: 12,
      backgroundColor: t.inputBg,
      color: t.text,
      textAlignVertical: "center",
      fontSize: 16,
      opacity: 0.99,
      backfaceVisibility: "hidden",
    },
    primaryBtn: {
      height: 48,
      paddingHorizontal: 16,
      borderRadius: 12,
      alignItems: "center",
      justifyContent: "center",
    },
    primaryBtnText: { color: "white", fontWeight: "700" },
    card: {
      backgroundColor: t.card,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: t.border,
      padding: 16,
    },
    helper: { color: t.subtle, textAlign: "center", marginTop: 12 },
    meta: { fontSize: 12, color: t.subtle },
    progressOuter: {
      height: 8,
      borderRadius: 999,
      backgroundColor: paletteLight.track,
      overflow: "hidden",
    },
    progressOuterDark: {
      height: 8,
      borderRadius: 999,
      backgroundColor: paletteDark.track,
      overflow: "hidden",
    },
    progressInner: { height: 8, borderRadius: 999 },
    pill: {
      paddingVertical: 8,
      paddingHorizontal: 10,
      borderRadius: 12,
      borderWidth: 1,
    },
    headerBtn: {
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: t.border,
      backgroundColor: t.card,
    },
    headerBtnText: { fontSize: 12, fontWeight: "700", color: t.text },
    // Settings sheet styles
    modalBackdrop: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.35)",
      justifyContent: "flex-end",
    },
    sheet: {
      backgroundColor: t.light,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      padding: 16,
      paddingBottom: 24,
    },
    sectionTitle: {
      fontSize: 14,
      fontWeight: "700",
      color: t.subtle,
      marginBottom: 8,
      marginLeft: 8,
    },
    group: {
      backgroundColor: t.card,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: t.border,
      overflow: "hidden",
    },
    row: {
      minHeight: 48,
      paddingHorizontal: 16,
      alignItems: "center",
      flexDirection: "row",
      justifyContent: "space-between",
    },
    rowTitle: { fontSize: 16, color: t.text },
    rowRight: { fontSize: 16, color: t.subtle },
    divider: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: t.border,
      marginLeft: 16,
    },
  });
